### ISSUE TITLE
CPU percentage

### ISSUE THREAD

**Issue by generrosity** [MinimallyCorrect/TickProfiler#102]
Hello! Love you mod, and Scalda was very kind to take my suggestion for the Foolcraft3 pack recently set up. Love it and use it that much.

Noticed this when helping someone doing diagnostics; it looked as like "/profile c" was returning 500000.000%  instead of 50.0% - possibly multiplying rather than dividing by 100. Not sure if the 3 decimals were of significant relevance.

**Comment by LunNova** [comment]
Should be fixed now. `ThreadMxBean.getThreadCpuTime` wasn't guaranteed to reset at 0 when thread CPU time monitoring was enabled, so it could have been dividing thread CPU time over the entire lifetime of the process by the time spent monitoring.
