### ISSUE TITLE
Can't download builds or build manually

### ISSUE THREAD

**Issue by josephyooo** [MinimallyCorrect/TickProfiler#104]
Jenkins link is dead and trying to build results in this [output](https://gist.github.com/Polokniko/2a1e81b91350cbd63bbb6991e41dde3b). Any other alternatives to this if this doesn't get fixed?

**Comment by LunNova** [comment]
The curseforge versions should be fine: https://minecraft.curseforge.com/projects/tickprofiler

I'll look at the jenkins issue soon, nginx seems to have died.

To build without access to my maven repo you'll need to build the projects it depends on and add them to your local maven repo.

**Comment by LunNova** [comment]
Fixed.
