### ISSUE TITLE
nallar.me seems to be down

### ISSUE THREAD

**Issue by JiDW** [MinimallyCorrect/TickProfiler#108]
Hey there!

It looks like your host is down, I can't access Jenkins and when trying to build the source myself, I get an error trying to download something from repo.nallar.me

Thanks for your help!

**Comment by LunNova** [comment]
Internet connection down, not physically present at the moment to check why.

Should sort it in a few hours

**Comment by JiDW** [comment]
Thanks!

**Comment by LunNova** [comment]
Sorted now

**Comment by WesleyVanNeck** [comment]
@nallar its down again

**Comment by AyOne** [comment]
@nallar still down

**Comment by LunNova** [comment]
@AyOne it's fixed
