### ISSUE TITLE
Crash with TickProfiler & Sponge

### ISSUE THREAD

**Issue by Aiidoneus** [MinimallyCorrect/TickProfiler#113]
Hello,
I was redirected here that Tickprofiler 1.12-0.0.7 is currently incompatible with SpongeForge due to the mixin 0.8 update. If you can, I would very much like to see an update to fix this.

SpongeForge version: spongeforge-1.12.2-2838-7.1.11-RC4004.jar

Forge version: forge-1.12.2-14.23.5.2847-universal.jar

Java version: 1.8.0_201

Operating System: Linux

Crash report:
https://gist.github.com/Aiidoneus/b0fdb582ad7149748d499e71ba5864de

Let me know if you need any other information and Thank you in advance!

https://github.com/SpongePowered/SpongeForge/issues/3096 for reference

**Comment by Scratchman** [comment]
I can confirm this. I just spent the last hour trying to find out which mod was doing it. Today i added a few server side mods to the server and it proceeded to crash on start up. My crash report looks the same as the OP's report.

**Comment by Pangamma** [comment]
I can also confirm this. This is causing issues with the RLCraft modpack.

**Comment by clienthax** [comment]
https://github.com/MinimallyCorrect/ModPatcher/issues/20

**Comment by LunNova** [comment]
Try one of the new builds here: https://jenkins.nallar.me/job/TickProfiler/job/1.12/

(not sure if got pushed to curseforge, the plugin which pushes to it's unhappy. Impossible to leave a forgegradle build system alone for half a year and have it still work 😠 )

**Comment by Aiidoneus** [comment]
New build works. Thanks
