### ISSUE TITLE
[Question] Whats the kcauldron version for?

### ISSUE THREAD

**Issue by Slind14** [MinimallyCorrect/TickProfiler#30]
Hey,

I have been using the normal forge version without any issues with kcauldron. Might I ask what the branch aims to fix/improve?

**Comment by LunNova** [comment]
See [#29](https://github.com/nallar/TickProfiler/issues/29#issuecomment-168973520).

TL;DR: Needed compatibility branch due to KCauldron change, KCauldron reverted the change, not needed any more.

**Comment by Slind14** [comment]
ahh, we went ahead from the official kcauldron and didn't cherry pick that change :)
I guess the branch can be removed or the description adjusted to avoid confusion.

**Comment by LunNova** [comment]
Okay, I've disabled and added a message to that branch on jenkins.
