### ISSUE TITLE
Tickprofiler KCauldron Edition

### ISSUE THREAD

**Issue by ProsperCraft** [MinimallyCorrect/TickProfiler#32]
We are having this console spam with the KCauldron edition using Kcauldron when we run /profile e
http://pastebin.com/UnvRzA7d

**Comment by LunNova** [comment]
What versions of TP and KCauldron are you using?

On current KCauldron builds, using the standard 1.7.10 release should work.
Does it work, but give the console spam? Or completely broken?

**Comment by ProsperCraft** [comment]
TickProfiler-1.7.10.1.jar  (kcauldron edition)
This server is running Cauldron version 1.7.10-1566.UNOFFICIAL (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

Also as a sidebar, I loved your tickthreading, it was amazing, you are a genius!

**Comment by ProsperCraft** [comment]
Just installed the non KCauldron version and it works fine like the old one did.

**Comment by LunNova** [comment]
Great.

I've added the warning notice on Jenkins again. Looks like the multi-branch plugin is removing the description when it syncs branches. Need to get it to stay, or maybe just delete that branch.

```
Obsolete KCauldron specific version.

<h2>Please use the standard 1.7.10 build.</h2>

<h2>Do not use this version unless you are using an old KCauldron version and encounter <a href="https://github.com/nallar/TickProfiler/issues/29">Issue #29</a></h2>
```
