### ISSUE TITLE
Tiny issue

### ISSUE THREAD

**Issue by ghost** [MinimallyCorrect/TickProfiler#37]
TickProfiler fails to load up and throws that error.

http://pastebin.com/WVuqef7D

**Comment by LunNova** [comment]
Let me guess... @Robotia still hasn't removed the check which disables TickProfiler? :P

That error will happen if the CoreMod part of TP loads but the Mod doesn't. I saw it before when I forgot to add `-Dthermos.tickprofiler.disable=false`.

**Comment by ghost** [comment]
Ah, shit, no he didn't. My bad, I should've went there first.

**Comment by sameer** [comment]
WOOPS doing that right now

**Comment by LunNova** [comment]
Closed by TCPR/Thermos@692abef9f4930edac.
