### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by KasperFranz** [MinimallyCorrect/TickProfiler#38]
Is it possible to add the ability to have permissions so it is possible to give admins (there doesn't have OP) access to profile commands :)

**Comment by LunNova** [comment]
Which permissions system are you using?

**Comment by KasperFranz** [comment]
Permission x 
But an implementation should be the same :) 
This is regarding the 1.7 version 

Den 25/02/2016 6.50 PM skrev Ross Allan notifications@github.com:

Which permissions system are you using?

**Comment by LunNova** [comment]
If you're using KCauldron that should already work. There will be a log message during startup (part of cauldron) which indicates the node it has assigned a node to the command. For example:

```
[INFO] Registered command profile with permission node nallar.tickprofiler.minecraft.commands.ProfileCommand
```

**Comment by KasperFranz** [comment]
Oh I didn't even know that,  that's quite nice,  thank you :)
