### ISSUE TITLE
Classloading crash during startup

### ISSUE THREAD

**Issue by kittykiller** [MinimallyCorrect/TickProfiler#39]
http://pastebin.com/mLce6aNN

**Comment by LunNova** [comment]
Diagnosing classloading issues can be a massive pain.

It would be really helpful if you could upload a zip of your server folder for me to test with. Failing that, what modpack are you using?

**Comment by kittykiller** [comment]
It seems to be an issue with Forge Essentials. http://ci.forgeessentials.com/job/FE/

My server file is ~35GB so that might not be a good idea lol.

Modpack is https://www.atlauncher.com/pack/DNSTechpack/

**Comment by kittykiller** [comment]
If this help "TickProfiler-1.7.10.jenkins.5" works but any version after that doesn't.

**Comment by LunNova** [comment]
> My server file is ~35GB so that might not be a good idea lol.

Oh, not including the worlds - just mods/configs/server jars/libraries.

> If this help "TickProfiler-1.7.10.jenkins.5" works but any version after that doesn't.

Afraid not - after that version I swapped to a new hook system which uses ModPatcher instead of doing hacky things with the tileentity/entity lists. That doesn't really narrow it down much.

**Comment by kittykiller** [comment]
https://dl.dropboxusercontent.com/u/664153/server1.7z

**Comment by LunNova** [comment]
Possible fix in TickProfiler build 27. [ModPatcher/31814177](https://github.com/nallar/ModPatcher/commit/3181417764819ed5bf9ff495171cd2d05c422e08)
