### ISSUE TITLE
profile c command broken

### ISSUE THREAD

**Issue by Brend-Smits** [MinimallyCorrect/TickProfiler#46]
I'm standing in a chunk full of ticking bluepower items and it doesn't see them as Tile entities.
https://gyazo.com/7890a4713483fbc8e546e4480d86f5f4

Running Tekkit Legends modpack if it matters.
Running version: TickProfiler-1.7.10.jenkins.29.jar

**Comment by LunNova** [comment]
Sorry about the late fix on this one. I said I'd fix it over the weekend in Discord chat when you first made it, but I became quite ill and forgot about it.

:(

edit: and I'm a derp. Fixed it for 1.8.9 but not in 1.7.10, will do that soon.

edit 2: Fixed in 1.7.10 branch now.
