### ISSUE TITLE
Minecraft 1.10.2 Support

### ISSUE THREAD

**Issue by AfterRebelion** [MinimallyCorrect/TickProfiler#51]
Mod won't load on forge for 1.10.2

[main/ERROR] [FML/]: The coremod nallar.tickprofiler.minecraft.CoreMod is requesting minecraft version 1.10 and minecraft is 1.10.2. It will be ignored.

**Comment by LunNova** [comment]
The inability to supply a range of acceptable versions for coremods is annoying. The only options are to support everything and get a warning in the logs, or to support one exact version string.

:/

I'll make a 1.10.2 branch.

**Comment by LunNova** [comment]
1.10.2 branch up, build on Jenkins. Haven't tested it, busy right now. Does it work?

**Comment by AfterRebelion** [comment]
It works now, thanks!
