### ISSUE TITLE
Incompatibility with Thermos and TickProfiler tile entity listings

### ISSUE THREAD

**Issue by ghost** [MinimallyCorrect/TickProfiler#52]
Hello Nallar,

When using the latest build of Thermos (Version 57), we experience a rather bizarre bug in which tile entities will stop working after about 2 minutes of the world loading. They will halt all function and only work when the chunk is loaded/unloaded for about two minutes. Upon removing Tickprofiler, they no longer had this issue. [Thermos build version 56](https://github.com/CyberdyneCC/Thermos/releases) changed how it handles entities and TEs, which may be part of this issue, since older versions before this still work. The logs are not extremely helpful but I have captured what I can below.

Thermos Version: Latest at v 57
Tick Profiler Version: TickProfiler-1.7.10.37.jar
Logs: http://pastebin.com/iTNS7rHc

Please let me know if you need anything else! :)

**Comment by LunNova** [comment]
> TickProfiler-1.7.10.37.jar

??? Where did you get that? That's not a version which is on the build service.

This should work fine, grab the latest version.

**Comment by LunNova** [comment]
Oh, it is a real version. Just from 25-Sep-2014 13:33 when the build service version numbers were different.

Reporting bugs while using a 2 year old build = :/

**Comment by ghost** [comment]
I am sorry, I don't have words for my stupidity. Have a good day.

**Comment by LunNova** [comment]
It's okay. Mistakes happen.
