### ISSUE TITLE
sponge 1.10.2?

### ISSUE THREAD

**Issue by AussieWarGod** [MinimallyCorrect/TickProfiler#56]
any chance of getting this ported to sponge 1.10.2?

**Comment by LunNova** [comment]
What's broken with Sponge?

**Comment by AussieWarGod** [comment]
My bad, i hadnt realised it was already compatible xD

In fact, it is already on the server i was looking at it for.

I'm just shopping around for extensive tick profilers as 1.10.2 is goving us issues and we are trying to locate the issue.

Sorry about that =^_^=
