### ISSUE TITLE
Permission node?

### ISSUE THREAD

**Issue by Y0ungSandwich** [MinimallyCorrect/TickProfiler#59]
Is their a permission node to add? Using Luckperms with sponge. Cant run any commands in game which doesn't help much.

**Comment by LunNova** [comment]
No, TickProfiler does not have any permission nodes.

By default some commands are only available for /opped users. You can change this in the config file.

**Comment by Y0ungSandwich** [comment]
Yeah it's just with permissions on sponge OP does nothing and everything is permission based after that

Get Outlook for Android<https://aka.ms/ghei36>



On Wed, Jan 18, 2017 at 7:26 AM -0500, "Ross Allan" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #59<https://github.com/nallar/TickProfiler/issues/59>.

**Comment by LunNova** [comment]
Try changing the settings not to require OP in the config file.

**Comment by LunNova** [comment]
Closing due to combination of "not my problem" (I don't create permission nodes, if your sponge plugin breaks my mod then that's not my fault), and user not trying turning off the config options to require /op.

**Comment by Y0ungSandwich** [comment]
I did,  doesnt really break it and didn't really want users to have access to tps.  Kind of a bad attitude I'll find another tool thanks.

**Comment by Y0ungSandwich** [comment]
I did,  doesnt really break it and didn't really want users to have access to tps.  Kind of a bad attitude I'll find another tool thanks.

**Comment by LunNova** [comment]
You didn't reply to me to let me know that that worked.

I can't add a permissions node without introducing a dependency on sponge which is unacceptable for most users of this mod. If there's a bug here it's that sponge/the permission system you're using for sponge doesn't allow you to configure permissions for mod commands.

**Comment by LunNova** [comment]
Try adding permissions for `TickProfiler.command.profile` or possibly `tickprofiler.command.profile`. I'm not sure which capitalisation will work or if it's actually case sensitive.

It turns out that sponge automatically creates permission nodes for mod commands:

> For any Forge mods that use the vanilla command API, command permissions are provided in the form `<modid>.command.<commandname>`.

**Comment by Magi1053** [comment]
For future reference, I was able to get `tickprofiler.command.profile` to work
