### ISSUE TITLE
Results are empty after running /profile e

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickProfiler#67]
After running a /profile e, the results are left entirely empty.

> [00:48:34] [TickProfiler/INFO] [TickProfiler/]: 
TPS: 20.0
Single Entity | Time/Tick | %
Chunk | Time/Tick | %
All Entities of Type | Time/Tick | %
Average Entity of Type | Time/tick | Calls

Minecraft 1.10.2, Forge 12.18.3.2254

Log file is attatched.
[fml-server-latest.txt](https://github.com/nallar/TickProfiler/files/907264/fml-server-latest.txt)

**Comment by LunNova** [comment]
Caused by an incompatibility with Asie's classcachetweaker.

First, make sure you're using the latest version of that in case it's already fixing it. Failing that I need to ask @asiekierka and/or find a workaround.

Can you confirm that removing classcachetweaker allows tickprofiler to work?

**Comment by asiekierka** [comment]
Any non-stateless IClassTransformer will not function correctly with ClassCacheTweaker, sadly.

**Comment by Puremin0rez** [comment]
Ah yes, it being ClassCacheTweaker makes a lot of sense since it is quite a hack.

I can confirm that removing it indeed fixes the problem. I'm on the latest version for both ClassCacheTweaker and TickProfiler, so a conflict does indeed still exist.

Thanks, nallar :)

**Comment by LunNova** [comment]
Should now be fixed. Steps to test:

* Update TickProfiler
* Delete ClassCacheTweaker's classCache.dat (probably not necessary, should detect this)
* Start server/client and test profile command

**Comment by DDzwiedziu** [comment]
I'm getting the same problem, but not with ClassCacheTweaker (unless ~zips~ jars did not contain such class name nor classChache.dat was found). Tried Jenkins versions 31 and 32, both times I get a exception as pasted below (full logs also attached).

Tested in Foolcraft 1.3.2 with custom modifications.

`[19:40:58] [main/INFO] [ModPatcher/]: Transformers: [net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
@6bff19ff, TransformerWrapper(net.minecraftforge.fml.common.asm.transformers.BlamingTransformer, FMLCorePlugin), Transf
ormerWrapper(net.minecraftforge.fml.common.asm.transformers.SideTransformer, FMLCorePlugin), TransformerWrapper(net.min
ecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer, FMLCorePlugin), TransformerWrapper(net.minecraftf
orge.fml.common.asm.transformers.EventSubscriberTransformer, FMLCorePlugin), TransformerWrapper(com.brandon3055.brandonscore.asm.ClassTransformer, Brandon's Core), TransformerWrapper(codechicken.lib.asm.ClassHeirachyManager, CCLCorePlugin), TransformerWrapper(codechicken.lib.asm.CCL_ASMTransformer, CCLCorePlugin), TransformerWrapper(invtweaks.forge.asm.ContainerTransformer, FMLPlugin), TransformerWrapper(codechicken.nei.asm.NEITransformer, NEICorePlugin), TransformerWrapper(landmaster.plustic.asm.Transform, PlusTiC), net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer@41e1455d, me.nallar.modpatcher.ModPatcherTransformer$ClassTransformer@4e558728, net.minecraftforge.fml.common.asm.transformers.AccessTransformer@5eccd3b9, invtweaks.forge.asm.ITAccessTransformer@4d6f197e, net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer@6ef7623, net.minecraftforge.fml.common.asm.transformers.ItemStackTransformer@64e1dd11, TransformerWrapper(cofh.asm.CoFHClassTransformer, CoFH Loading Plugin), TransformerWrapper(cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager, CoFH Loading Plugin), TransformerWrapper(net.malisis.core.util.chunkcollision.ChunkCollisionTransformer, MalisisCorePlugin), TransformerWrapper(net.malisis.core.util.chunkblock.ChunkBlockTransformer, MalisisCorePlugin), TransformerWrapper(net.malisis.core.renderer.transformer.MalisisRendererTransformer, MalisisCorePlugin), TransformerWrapper(net.malisis.core.renderer.icon.asm.TextureMapTransformer, MalisisCorePlugin), TransformerWrapper(net.malisis.core.util.clientnotif.ClientNotifTransformer, MalisisCorePlugin), TransformerWrapper(lumien.resourceloader.asm.ClassTransformer, LoadingPlugin)]
java.lang.Throwable
        at me.nallar.modpatcher.LaunchClassLoaderUtil.dumpTransformersIfEnabled(LaunchClassLoaderUtil.java:84) [ModPatcher.jlib:?]
        at me.nallar.modpatcher.ModPatcherTransformer.initialiseClassLoader(ModPatcherTransformer.java:116) [ModPatcher.jlib:?]
        at me.nallar.modpatcher.ModPatcher.initialiseClassLoader(ModPatcher.java:161) [ModPatcher.class:?]
        at me.nallar.modpatcher.ModPatcherSetup.injectData(ModPatcherSetup.java:16) [TickProfiler-1.10.2.jenkins.32.jar:?]
        at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:165) [forge-1.10.2-12.18.3.2281-universal.jar:?]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62) [forge-1.10.2-12.18.3.2281-universal.jar:?]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31) [forge-1.10.2-12.18.3.2281-universal.jar:?]
`


[fml-server-latest.txt](https://github.com/nallar/TickProfiler/files/981812/fml-server-latest.txt)

**Comment by LunNova** [comment]
Error isn't an error, it misleadingly included a stack trace when it shouldn't. Removed that now.

Patch errors later due to javassist trying to get deobfed minecraft classes and instead getting obfuscated classes.

Can you try deleting ModPatcher,jlib from the mods folder, then start the server?

If it still isn't working, can you find the file "libraries/minecraft_stubs.jar" in the server folder and send it, if it exists?

**Comment by DDzwiedziu** [comment]
Deleting ModPatcher.jlib worked. Thanks
