### ISSUE TITLE
Profile results are empty

### ISSUE THREAD

**Issue by LXGaming** [MinimallyCorrect/TickProfiler#70]
Minecraft 1.10.2
SpongeForge 2344
TickProfiler 47

Doing profile returns no results, I've tried removing ModPatcher.jlib, and deleting files from the libraries folder which seemed to belong to ModPatcher with no luck.

**Comment by LunNova** [comment]
Fixed, bug in ModPatcher. https://github.com/MinimallyCorrect/ModPatcher/commit/5d3ae567ac1a803998ef1f5fdee979b239d24d87

Try TickProfiler 48.

**Comment by LunNova** [comment]
Scratch that, try 49. 48 didn't pick up the new version of ModPatcher due to a caching issue.

**Comment by LXGaming** [comment]
Just tested and can confirm profile now returns results.

Absolutely awesome, Thank you so much.
