### ISSUE TITLE
Request: Add Tick Profiler to Curse

### ISSUE THREAD

**Issue by sandalle** [MinimallyCorrect/TickProfiler#71]
Would you add Tick Profiler to [Curse Mods](https://minecraft.curseforge.com/mc-mods) (now Twitch) so that we may easily add and manage it in modpacks? :)

Some documents to help:
https://github.com/matthewprenger/CurseGradle
https://www.curseforge.com/docs/api
https://github.com/McJty/RFTools/blob/1.11/build.gradle

**Comment by Shybella** [comment]
I would stay far away from Curse.

**Comment by LunNova** [comment]
@Shybella why?

I was planning to do this at some point. To be honest the only reason I didn't do it last week is that creating a project there requires a logo and I got distracted after it wouldn't let me skip that. :P

Publishing to curse gives an alternate location to download my mods, and I wouldn't be activating curse rewards (or whatever it's called).

**Comment by japherwocky** [comment]
I came here to ask for this also.  Curse is really nice for making private mod packs, which need something like this.  (I found this looking for a 1.10 Opis!)

**Comment by LunNova** [comment]
Done. https://minecraft.curseforge.com/projects/tickprofiler

**Comment by sandalle** [comment]
> Warning: This project is experimental. Its files will not synchronize across the Curse network.

I think this means that it won't show up in the Curse launcher for easy including in a modpack. We can still manually add it and point to this profile for permission, thank you. :)

Edit: It's "live" now, thanks! :)

**Comment by LunNova** [comment]
It's submitted for approval but I don't know how long that will take.

edit: Not very long :)
