### ISSUE TITLE
Request: Add coordinates to lag spike profiler

### ISSUE THREAD

**Issue by CathalCraft** [MinimallyCorrect/TickProfiler#74]
It would be very beneficial to add coordinates to the lag spike profiler, so I can teleport to the coordinate that is causing the lag spike and resolve the issue there.

**Comment by morfie78** [comment]
Agreed!  That would be super helpful.

**Comment by LunNova** [comment]
Can't be done - the lag spike profiler only knows the stack trace of the main thread at the time of the spike.

I don't think that getting from that to being able to blame a specific location in the world is possible.

**Comment by LunNova** [comment]
Closing as wontfix. I would like to do this, but I don't think it can be done so there is no point in leaving the issue open forever.

:(

**Comment by morfie78** [comment]
It's fine, thank you for a great plugin, nonetheless!   Would looking at TickProfiler's lag spike stack traces, and making an event listener (in another plugin) for that event work?  Event listeners will return the location, and then we can use that info to find the location of the issue.  I've successfully done it before for a specific event that was causing lag on my server.

**Comment by cjm721** [comment]
What you are saying would only work if that event had location information. The Stack-trace will tell you what mod's event handler it was in so if that event has location information you could try. If the lagging event is also on priority=highest you will have issues as you have no way to guarantee your code runs first to be able to capture the information.
