### ISSUE TITLE
Profile server/world tick events

### ISSUE THREAD

**Issue by LunNova** [MinimallyCorrect/TickProfiler#75]
@Slind14 

@nallar On 1.10 there are no longer so many mods that perform heavy lifting outside the entity and tile entity tick. Unfortunately there are still a few and hence they are unseen by tick profiler. Do you think mod level support would be applicable to implement for these rare cases?

EnderIO would be the main one for example.

![](https://cdn.discordapp.com/attachments/313371711632441344/339423322548731904/unknown.png)

**Comment by DarkBlade177** [comment]
Just for curiosity, what is this program that you use for profilling ?

**Comment by Slind14** [comment]
YourKit. But I would recommend visual VM for CPU profiling. There is not
really any major difference and it is free.

**Comment by DarkBlade177** [comment]
@Slind14 One last question to stop this non-related conversation.

Can i use VisualVM on a vps?
My server is hosted on an ubuntu 16.04 

Can i profile even if it is not on my computer?

**Comment by LunNova** [comment]
Rather than adding specific support for these events this will be covered under #78
