### ISSUE TITLE
TickProfil permission 

### ISSUE THREAD

**Issue by bdspark** [MinimallyCorrect/TickProfiler#76]
Hello, I have heard from someone that your TickProfiling is better than others. It do great job for finding lag. So I want to try it. But I couldn't find any permissions in the wiki and only has commands. Can you please provide permissions for those commands?

Thanks in advance.

**Comment by LunNova** [comment]
Here's a new wiki page.

https://github.com/MinimallyCorrect/TickProfiler/wiki/Permission-Nodes
