### ISSUE TITLE
[Just a question, please close this]

### ISSUE THREAD

**Issue by MainFreak** [MinimallyCorrect/TickProfiler#77]
I noticed that, when used in a modpack on the client, this utility generates a file called "# LibLoader" in the mods folder. So my question is if this file can be used in modpacks or not since Curse does not recognize it as a valid mod. The utility seems to be functional in singleplayer as well so I would really prefer to keep it in my pack.

**Comment by LunNova** [comment]
That file will be automatically extracted every time you launch with TickProfiler or another mod which uses LibLoader installed. It does not need to be redistributed - it will be automatically created when needed - but you can redistribute it if that makes things easier.

**Comment by MainFreak** [comment]
So I technically can just delete it before uploading the pack to Curse. Thank you very much

**Comment by LunNova** [comment]
Yes, that will work fine.
