### ISSUE TITLE
[1.12.2] Tick Profiler 1.12-0.0.1 works, but is not marked as such on Curse

### ISSUE THREAD

**Issue by sandalle** [MinimallyCorrect/TickProfiler#85]
[Tick Profiler 1.12-0.0.1](https://minecraft.curseforge.com/projects/tickprofiler/files/2482605) works on MC 1.12.2 (Forge Mod Loader 14.23.0.2515), but is not marked as such on Curse disallowing modpacks from using it.

**Comment by LunNova** [comment]
Fixed, thanks.

**Comment by sandalle** [comment]
Thank you for the quick turn-around @nallar . :)
