### ISSUE TITLE
Horizons server cannot initialize with TickProfiler installed

### ISSUE THREAD

**Issue by tolly765** [MinimallyCorrect/TickProfiler#86]
Whenever we try to start up our FTB Horizons server (running on SpongeForge version spongeforge-1.12.2-2503-7.0.0-BETA-2710) with TickProfiler enabled, it crashes on the first few seconds of initialising and throws [this into console.](https://pastebin.com/YhYZ59si) This behavior only occurs when TickProfiler is installed on the 1.12 version, and not on 1.10.2 (we have it working flawlessly on our SF3 server and it's a god send on there).

SpongeForge Version: spongeforge-1.12.2-2503-7.0.0-BETA-2710
TickProfiler Version: TickProfiler-1.12-0.0.1

If it helps, we also use [Pterodactyl](https://pterodactyl.io) to sort our servers into containers.

**Comment by cjm721** [comment]
Must be a sponge thing again. I am running default forge for H3 no issues.

**Comment by tolly765** [comment]
Further testing in a fresh SpongeForge server (only tickprofiler as an external plugin/mod, everything else was in Horizons III) shows TickProfiler functioning normally. Perhaps there is a discrepancy in the live version.

I’ll let you know if we find something later

**Comment by LunNova** [comment]
Could be a file permissions issue or something else preventing LibLoader from working. Does Pterodactyl make the mods folder a read only volume?

There should be a file called `# LibLoader.jar` in your mods folder. If there isn't, try manually creating it by extracting `LibLoader.jar` from inside of TickProfiler's jar, then renaming it to `# LibLoader.jar`.

**Comment by tolly765** [comment]
I apologise for the delays in a reply, but we have found the following out:

- Pterodactyl does not make the folder read only when the server is running
- We tried your fix with `# LibLoader.jar` but to no avail - same error as before
- The error specifically states that Forge can't lock the base of our container, so I'm not sure what's going on there
- We have other "mixin" mods (mods that don't originate from the pack itself) working just fine, so we don't think it's the Tickprofiler mod's fault.

However, I am now out of ideas to try to fix it... and the fact that a fresh spongeforge server running on my local machine works fine baffles me.

**Comment by cjm721** [comment]
Running normal JDK and java security permissions?

**Comment by tolly765** [comment]
Normal JDK and Java security settings

**Comment by tolly765** [comment]
Alright, we've been tearing our heads out over this, and we _finally_ got it working. Turns out that it was because TickProfiler was being loaded as an extramod through forge (using parameter `--mods=""` and it did NOT like that at all. Took us having to test over the course of a few days (due to other projects being thrown in the mix as well) but we now know it works fine.

Sorry for keeping you in the dark @nallar
