### ISSUE TITLE
Profiling chunks in latest 1.12.2 compat version

### ISSUE THREAD

**Issue by Electrofried** [MinimallyCorrect/TickProfiler#89]
I am trying to use tick profiler on 1.12.2, it is working fine, but I can't seem to get it to profile just one chunk anymore, although I am sure this worked with past versions. Checked all the options that /profile lists and none of them seem to list the ability to restrict profiling to one chunk. 
The wiki lists /profile c (and this is what I remember using) however that gives entity counts now and can also only be restricted to dimensions. 
It was super useful to profile a dimension to find the worst chunks then restrict it to that chunk and just profile those in order to track down issues. Is this feature removed/coming back or am I just being special?

**Comment by xorinzor** [comment]
Can confirm, `/profile c` is entity count, not Chunk information.

Additionally, there is no way using `/profile e` to tell what chunk contains the most items, or where items are generally coming from.

**Comment by ArcanoxDragon** [comment]
Can confirm this as well, plus `/profile e` does not accept the `time=` parameter like it should (all values still result in 30 seconds of profiling) and it does not measure TileEntities like the source code implies it should.

**Comment by Fatmice** [comment]
> Can confirm this as well, plus /profile e does not accept the time= parameter like it should (all values still result in 30 seconds of profiling) and it does not measure TileEntities like the source code implies it should.

How did you issue it? 
/profile e 60  will profile for 60s
/profile e 60 0 will profile overworld for 60s
/profile e 60 0 10 will profile overworld for 60s and list 10 things

**Comment by LunNova** [comment]
`profile c` is now for entity counting. This is intentional and was changed as part of 95a252eb62a84c which standardised profile command handling.

I was planning to add single chunk profiling as an option for `profile e`, it seemed more logical than a separate command. Unfortunately I haven't had much time to work on TickProfiler recently and have not yet added this.

**Comment by tolly765** [comment]
We can wait, take your time nallar 😄

**Comment by LunNova** [comment]
Use `/profile e chunk=current` in the latest version

**Comment by Dimentive** [comment]
@nallar That command doesn’t work.

**Comment by Dimentive** [comment]
@nallar That command doesn’t work. Has this been changed?

**Comment by LunNova** [comment]
>Has this been changed?

always been wrong, i messed up in that comment. 😢

**Comment by Dimentive** [comment]
No worries.
