### ISSUE TITLE
Silly Question

### ISSUE THREAD

**Issue by Boolyman** [MinimallyCorrect/TickProfiler#92]
What do the abbreviations at the top of the /tps columns mean?  I assume the E = Entities, the TE = Tile Entities, and the C = ?  Chunks?  The numbers don't seem to reflect actual in world counts if thats what they mean... like it says I have 700 Entities at the moment?  And 1300 chunks?  Im the only person on this world, how can there be 1300 chunks loaded?

**Comment by LunNova** [comment]
That's correct.

Forced chunks, spawn area, actual chunks in view of the player can add up fast.

`/profile c` will count entities so you can see what makes up those 700.
