### ISSUE TITLE
1.5.2 TickProfiler-1.5.2/build.xml:156: exec returned: 127

### ISSUE THREAD

**Issue by Fudster** [MinimallyCorrect/TickProfiler#94]
I am trying to compile 1.5.2 I get the following error:

``amp@vps:~/l/TickProfiler-1.5.2$` ant
Buildfile: /home/amp/l/TickProfiler-1.5.2/build.xml

version-provided:

version-not-provided:

initialize-version:

download-forge:

download-maven-ant-tasks:

download-files:

setup:

download-libs:

compile:
   [delete] Deleting directory /home/amp/l/TickProfiler-1.5.2/build/classes
    [mkdir] Created dir: /home/amp/l/TickProfiler-1.5.2/build/classes
     [exec] sh: 0: Can't open recompile.sh

BUILD FAILED
/home/amp/l/TickProfiler-1.5.2/build.xml:156: exec returned: 127

Total time: 0 seconds
`amp@vps:~/l/TickProfiler-1.5.2$``

**Comment by LunNova** [comment]
The build script will try to download forge to build/forge and mcp to build/forge/mcp.

It has been a very long time since I last built a version this old. I expect the download links it uses are no longer valid.

If it did successfully download, maybe the recompile.sh file in build/forge/mcp needs set executable. (with `chmod +x`)

**Comment by Fudster** [comment]
I managed to download the libs manually. 

Can't seem to find recompile.sh 

I even searched for it with:  find . -name recompile.sh

**Comment by LunNova** [comment]
Try the version of MCP for 1.5.2 from the [minecraft wiki](https://minecraft.gamepedia.com/Programs_and_editors/Mod_Coder_Pack#Downloads).

**Comment by Fudster** [comment]
Whee does the file go? (mcp751.zip)

**Comment by LunNova** [comment]
Extract the contents inside the `build/forge/mcp` folder.

**Comment by Fudster** [comment]
I get the following: 

compile:
   [delete] Deleting directory /home/amp/l/TickProfiler-1.5.2/build/classes
    [mkdir] Created dir: /home/amp/l/TickProfiler-1.5.2/build/classes
     [exec] == MCP 7.51 (data: 7.51, client: 1.5.2, server: 1.5.2) ==
     [exec] !! Please install either wine or astyle for source cleanup !!
     [exec] # found ff, ff patches, srgs, name csvs, doc csvs, param csvs, renumber csv, astyle config
     [exec] !! Can not find client sources, try decompiling !!
     [exec] !! Can not find server sources, try decompiling !!
     [exec] == MCP 7.51 (data: 7.51, client: 1.5.2, server: 1.5.2) ==
     [exec] !! Please install either wine or astyle for source cleanup !!
     [exec] # found ff, ff patches, srgs, name csvs, doc csvs, param csvs, renumber csv, astyle config
     [exec] > Creating Retroguard maping files
     [exec] > Creating Retroguard config files
     [exec] !! Can not find client md5s !!
     [exec] !! Can not find server md5s !!

BUILD FAILED
/home/amp/l/TickProfiler-1.5.2/build.xml:170: /home/amp/l/TickProfiler-1.5.2/build/forge/mcp/reobf/minecraft does not exist.

**Comment by LunNova** [comment]
That probably happens if forge's install script didn't run.

Try running `ant setup`. If that doesn't help, go into build/forge and run install.sh in there yourself.

**Comment by Fudster** [comment]
amp@vps:~/l/TickProfiler-1.5.2/build/forge$ ./install.sh
================ Forge ModLoader Setup Start ===================
Download of mcp7.51.zip failed md5 check, deleting

**Comment by Fudster** [comment]
Eh. That last error was a ID10T error. I have this now:

== MCP 7.51 (data: 7.51, client: 1.5.2, server: 1.5.2) ==
"scalac" is not found on the PATH.  Scala files will not be recompiled
FATAL ERROR
Traceback (most recent call last):
  File "/home/amp/l/TickProfiler-1.5.2/build/forge/mcp/runtime/decompile.py", line 50, in decompile
    commands = Commands(conffile, verify=True, no_patch=no_patch)
  File "/home/amp/l/TickProfiler-1.5.2/build/forge/mcp/runtime/commands.py", line 202, in __init__
    self.readcommands(verify, no_patch=no_patch)
  File "/home/amp/l/TickProfiler-1.5.2/build/forge/mcp/runtime/commands.py", line 281, in readcommands
    output = self.runcmd('%s --version' % self.astyle).rstrip().split(' ')
  File "/home/amp/l/TickProfiler-1.5.2/build/forge/mcp/runtime/commands.py", line 1187, in runcmd
    process = subprocess.Popen(forklist, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, bufsize=-1)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Decompile Exception: 1

**Comment by LunNova** [comment]
If you don't intend to make any changes, the last build for 1.5.2 is here: https://jenkins.nallar.me/job/TickProfiler-1.5.2/

**Comment by Fudster** [comment]
I tried both wget and downloading the file in browser then uploading...Keep getting this.

Warning : Unable to parse manifest details for './Minecraft/plugins/TickProfiler-1.5.2-1.0.0.44.jar'
