### ISSUE TITLE
Version number not replaced in mcmod.info

### ISSUE THREAD

**Issue by Fireztonez** [MinimallyCorrect/TickProfiler#98]
I do a /profile s in my modpack for try to find the sourse of the lags I get, but for some reason, after that command, somes java error message is output in the chat. I imagine that's not intended!!

Here the logs, just after enter that command:
https://gist.github.com/Fireztonez/1a0eb9145b44c776e91c6dbfaff5f0ca

Other things, in the mod list : 
![image](https://user-images.githubusercontent.com/19277301/39330465-b9936b36-496f-11e8-9634-fa6fb36673de.png)
 

Version:
Minecaft : 1.12.2
TickProfiler: 0.0.4
Forge: 14.23.3.2669
Java: 1.8.0_171

Fireztonez

**Comment by LunNova** [comment]
That is normal output for `/profile s`. It shows stack traces of the main server thread while there appears to be a lag spike. If you are a developer this will help, it is maybe not very understandable for most users but there is not any good solution for this.

`/profile e` may be what you want.

The version not showing up correctly is a minor bug. It should not cause any problems.
